version: '3.8'

services:
  broker:
    build:
      context: .
      dockerfile: Dockerfile
    image: federated-catalog
    networks:
      db:
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8181:8181"
    environment:
      EDC_FLYWAY_REPAIR: 'false'
      EDC_DATASOURCE_DEFAULT_URL: 'jdbc:postgresql://postgres:5432/broker'
      EDC_DATASOURCE_DEFAULT_USER: 'postgres'
      EDC_DATASOURCE_DEFAULT_PASSWORD: 'password'

  postgres:
    image: postgres:14-alpine
    networks:
      db:
        aliases:
          - postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: broker
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready --username=postgres && psql --username=postgres --list"
      timeout: 10s
      retries: 20
      start_period: 0s


networks:
  db:
    internal: true
    external: false

volumes:
  postgres-data: