name: Build Image

on:
  push:
    branches:
      - 'feature/**'
      - 'fix/**'

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Project
        run: ./gradlew clean build

      - name: Login Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ GITHUB_ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Image
        uses: docker/build-push-action@v4
        with:
          context: ./launchers/postgres-prod
          file: ./launchers/postgres-prod/Dockerfile
          push: false
