name: Build and Publish Image

on:
  push:
    branches: ['develop']

jobs:
  increment-image-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Bump Version
        uses: remorses/bump-version@js
        with:
          version_file: ./launchers/VERSION
          prefix: image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-push-image:
    needs: increment-image-version
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Project
        run: ./gradlew clean build

      - name: Login Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Read Version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./launchers/VERSION

      - name: Image Tags
        id: image-tags
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/truzzt/federated-catalog
          tags: |
            type=raw,value=latest
            ${{ steps.version.outputs.content }}

      - name: Build and Push Image
        uses: docker/build-push-action@v4
        with:
          context: ./launchers/postgres-prod
          file: ./launchers/postgres-prod/Dockerfile
          push: true
          tags: ${{ steps.image-tags.outputs.tags }}
          labels: ${{ steps.image-tags.outputs.labels }}
